---
devices:
- hostname: R3
  vendor: arista
  clear_config: 'no'
  bgp:
    as_number: '65001'
    address_families:
    - type: ipv4
      networks:
      - ip: 30.30.30.0
        mask: '24'
      neighbors:
      - ip: 20.20.20.1
        remote_as: '65002'
